name: Quality audit

on: [pull_request]

env:
  GHR_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  eslint:
    name: eslint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Install JS dependencies
        run: yarn install
      - name: Run ESLint
        uses: reviewdog/action-eslint@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-check

  misspell:
    name: check / misspell
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: misspell
        uses: reviewdog/action-misspell@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-annotations
          fail_level: any
          locale: "US"
          exclude: |
            ./node_modules/*
            ./eslint*
            ./dist/*
            ./yarn.lock

  shellcheck:
    name: runner / shellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: shellcheck
        uses: reviewdog/action-shellcheck@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-annotations
          fail_level: any
          path: "."
          pattern: "*.sh"
          exclude: "./.git/*"

  yamllint:
    name: check / yamllint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: yamllint
        uses: reviewdog/action-yamllint@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-annotations
          fail_level: any
          yamllint_flags: '-d "{extends: default, rules: {truthy: disable}}" .'

  actionlint:
    name: runner / actionlint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: reviewdog/action-actionlint@v1
        with:
          reporter: github-pr-annotations
          fail_level: error
          level: warning

  alex:
    name: runner / alex
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: reviewdog/action-alex@v1
        with:
          reporter: github-pr-annotations
          fail_level: error
          level: warning
